version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker kube-iptables-tailer
          command: |
            if [[ $CIRCLE_TAG ]]
            then DOCKER_TAG=$CIRCLE_TAG
            else DOCKER_TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
            fi
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build -t honestica/kube-iptables-tailer:$DOCKER_TAG .
            docker push honestica/kube-iptables-tailer:$DOCKER_TAG
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
